openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /correctores/{id}:
    get:
      tags:
      - controlador-correctores
      description: Obtiene un corrector concreto
      operationId: getUsuario
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: El corrector existe
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Corrector'
        "404":
          description: El corrector no existe
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Corrector'
        "403":
          description: Acceso no autorizado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Corrector'
    put:
      tags:
      - controlador-correctores
      description: Actualiza un corrector
      operationId: actualizarUsuario
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: El corrector se ha actualizado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Corrector'
        "404":
          description: El corrector no existe
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Corrector'
        "403":
          description: Acceso no autorizado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Corrector'
    delete:
      tags:
      - controlador-correctores
      description: Elimina el corrector.
      operationId: eliminarUsuario
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: El corrector se ha elminado
        "404":
          description: El corrector no existe
        "403":
          description: Acceso no autorizado
  /correctores:
    get:
      tags:
      - controlador-correctores
      description: Obtiene la lista de correctores del sistema
      operationId: obtenerUsuarios_1
      parameters:
      - name: idConvocatoria
        in: query
        description: "ID de la convocatoria de la que se quiere los correctores. \t\
          Si no se indica, se obtienen todos los correctores del sistema."
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Devuelve la lista de correctores
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Corrector'
        "403":
          description: Acceso no autorizado
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Corrector'
    post:
      tags:
      - controlador-correctores
      description: Crea un nuevo corrector para la convocatoria vigente (que se pasa
        dentro del objeto)
      operationId: obtenerUsuarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CorrectorNuevo'
        required: true
      responses:
        "201":
          description: El corrector se crea correctamente
          headers:
            Location:
              description: URI del nuevo recurso
              style: simple
              schema:
                type: string
        "409":
          description: Hay un corrector con el mismo identificador de usuario
        "403":
          description: Acceso no autorizado
components:
  schemas:
    Corrector:
      type: object
      properties:
        id:
          type: integer
          format: int64
        identificadorUsuario:
          type: integer
          format: int64
        telefono:
          type: string
        maximasCorrecciones:
          type: integer
          format: int32
        materias:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/MateriaEnConvocatoria'
    MateriaEnConvocatoria:
      type: object
      properties:
        idMateria:
          type: integer
          format: int64
        idConvocatoria:
          type: integer
          format: int64
    CorrectorNuevo:
      type: object
      properties:
        identificadorUsuario:
          type: integer
          format: int64
        identificadorConvocatoria:
          type: integer
          format: int64
        telefono:
          type: string
        materia:
          $ref: '#/components/schemas/Materia'
        maximasCorrecciones:
          type: integer
          format: int32
    Materia:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
