openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /notificaciones/{id}:
    get:
      tags:
      - controlador-notificaciones
      description: Obtiene una notificación concreta
      operationId: getNotificacion
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: La notificación existe
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Notificacion'
        "404":
          description: La notificación no existe
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Notificacion'
        "403":
          description: Acceso no autorizado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Notificacion'
    put:
      tags:
      - controlador-notificaciones
      description: Actualiza una notificación
      operationId: actualizarNotificacion
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: La notificación se ha actualizado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Notificacion'
        "404":
          description: La notificación no existe
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Notificacion'
        "403":
          description: Acceso no autorizado
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Notificacion'
    delete:
      tags:
      - controlador-notificaciones
      description: Elimina la notifiación.
      operationId: eliminarNotificacion
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: La notificación se ha elminado
        "404":
          description: La notificación no existe
        "403":
          description: Acceso no autorizado
  /pendientes/abortar:
    post:
      tags:
      - controlador-notificaciones
      description: Permite abortar las notificaciones pendientes de envío de un determinado
        tipo. Si no se especifica el tipo se abortan todas las pendientes.
      operationId: abortarNotificacionesPendientes
      parameters:
      - name: tipo
        in: query
        description: Tipo de las notificaciones a abortar. Si no se indican se abortan
          todas las pendientes
        required: false
        schema:
          type: string
          enum:
          - ANUNCIO_NOTA_ESTUDIANTE
          - ANUNCIO_AULA_ESTUDIANTE
          - ANUNCIO_AULA_VIGILANTE
          - PASSWORD_RESET
      responses:
        "200":
          description: Se han abortado las notificaciones pendientes indicadas.
        "403":
          description: Acceso no autorizado
      security:
      - public: []
  /notificaciones:
    get:
      tags:
      - controlador-notificaciones
      description: "Obtiene la lista de notificaciones del sistema, filtrada de acuerdo\
        \ con los parámetros de consulta (si se usan)."
      operationId: obtenerNotificaciones
      parameters:
      - name: tipo
        in: query
        required: false
        schema:
          type: string
          enum:
          - ANUNCIO_NOTA_ESTUDIANTE
          - ANUNCIO_AULA_ESTUDIANTE
          - ANUNCIO_AULA_VIGILANTE
          - PASSWORD_RESET
      - name: estado
        in: query
        required: false
        schema:
          type: string
          enum:
          - PENDIENTE
          - ENVIADO
          - ABORTADA
          - ERROR
      responses:
        "200":
          description: Devuelve la lista de notificaciones
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notificacion'
        "403":
          description: Acceso no autorizado
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notificacion'
    post:
      tags:
      - controlador-notificaciones
      description: Crea una nueva notificación en el sistema
      operationId: crearNotificacion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificacionNueva'
        required: true
      responses:
        "201":
          description: La notificación se crea correctamente
          headers:
            Location:
              description: URI del nuevo recurso
              style: simple
              schema:
                type: string
        "403":
          description: Acceso no autorizado
components:
  schemas:
    Notificacion:
      type: object
      properties:
        id:
          type: integer
          format: int64
        asunto:
          type: string
        cuerpo:
          type: string
        emailDestino:
          type: string
        telefonoDestino:
          type: string
        programacionEnvio:
          type: string
          format: date-time
        medios:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
            - SMS
            - EMAIL
        tipoNotificacion:
          type: string
          enum:
          - ANUNCIO_NOTA_ESTUDIANTE
          - ANUNCIO_AULA_ESTUDIANTE
          - ANUNCIO_AULA_VIGILANTE
          - PASSWORD_RESET
        estado:
          type: string
          enum:
          - PENDIENTE
          - ENVIADO
          - ABORTADA
          - ERROR
        mensajeError:
          type: string
        momentoRealEnvio:
          type: string
          format: date-time
    NotificacionNueva:
      type: object
      properties:
        asunto:
          type: string
        cuerpo:
          type: string
        emailDestino:
          type: string
        telefonoDestino:
          type: string
        programacionEnvio:
          type: string
          format: date-time
        medios:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
            - SMS
            - EMAIL
        tipoNotificacion:
          type: string
          enum:
          - ANUNCIO_NOTA_ESTUDIANTE
          - ANUNCIO_AULA_ESTUDIANTE
          - ANUNCIO_AULA_VIGILANTE
          - PASSWORD_RESET
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
